# Generated by Django 5.1.5 on 2025-01-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyguide',
            name='guide_path',
            field=models.FileField(max_length=255, upload_to='study_guides/'),
        ),
    ]
